// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b3793d96-23ec-41ce-8501-04e974377057");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575360676);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575360796);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575360250);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575360436);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575360316);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575360556);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575361036);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575360916);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575360220);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a7e22ebf-4d9e-42ef-bd1e-ed3fa874437f}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575360000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575360356076");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575362144076");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575360231825");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575363831825");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575360287");
user_pref("browser.slowStartup.averageTime", 11147);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575360230053");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "c712b03176c046deba2c256b108424d5");
user_pref("extensions.blocklist.lastModified", "Mon, 02 Dec 2019 11:14:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575360678);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8f7c4007-37a1-4309-94cf-572672cbf86b\",\"screenshots@mozilla.org\":\"e668aa15-9059-4f6a-8d1e-5d7db5b1b6dc\",\"webcompat-reporter@mozilla.org\":\"fdf0b1cb-8758-4b3d-b7f5-daea4bf35c61\",\"webcompat@mozilla.org\":\"5d513cf2-2db4-4cee-935c-6c9e7b11aba4\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575360458);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575360452);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "a2e4875e-99f2-46e0-936a-026f280b87bd");
user_pref("security.sandbox.plugin.tempDirSuffix", "777f3063-e97d-4e66-8059-b71602cbc304");
user_pref("services.blocklist.addons.checked", 1575340680);
user_pref("services.blocklist.gfx.checked", 1575340680);
user_pref("services.blocklist.onecrl.checked", 1575340680);
user_pref("services.blocklist.pinning.checked", 1575340680);
user_pref("services.blocklist.plugins.checked", 1575340680);
user_pref("services.settings.clock_skew_seconds", 19573);
user_pref("services.settings.last_update_seconds", 1575340983);
user_pref("services.settings.main.language-dictionaries.last_check", 1575340680);
user_pref("services.settings.main.sites-classification.last_check", 1575340680);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575360285);
user_pref("toolkit.telemetry.cachedClientID", "f54f324c-ec7a-4c44-83fe-1dfa0b01b367");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
